project_name: traefik-oidc-wasm
version: 2

builds:
  - binary: plugin
    gobinary: go
    no_unique_dist_dir: true
    main: .
    ldflags:
      - ''
    goos:
      - wasip1
    goarch:
      - wasm

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^chore(deps):'
      - '^test:'
      - '^tests:'

archives:
  - id: traefik-oidc-wasm
    name_template: '{{ .ProjectName }}_v{{ .Version }}'
    format: zip
    files:
      - LICENSE
      - .traefik.yml
